#!/usr/bin/perl
use 5.014;
use warnings;
use strict;

print "Enter Radius : ";
chomp (my $radius = <STDIN>);
my $circumference = 2 * 3.14156 * $radius;
if ( $circumference < 0 ) {
   $circumference = 0;
}
say "Circumference = $circumference";
