#!/usr/bin/perl
use 5.014;
use warnings;
use strict;

print "Please Input String : ";
chomp( my $str = <STDIN> );
print "Please Input Number : ";
chomp( my $num = <STDIN> );
print $str = "$str\n" x $num; 
