#!/usr/bin/perl
use 5.010;
use warnings;
use strict;

# Modify the program from the previous exercise to use named captures instead
# of relying on $1. Update the code to display that label name, something like
# 'word' contains 'Wilma'.

while (<>) {                   # take one input line at a time
    chomp;
    if (/(?<word>\b\w*a\b)/i) {
        print "'word' contains '$+{word}'\n";  # the special match vars
    } else {
        print "No match: |$_|\n";
    }
}
