#!/usr/bin/perl
use 5.010;
use warnings;
use strict;

# Write a new program (not the test program!) that prints out any input line
# ending with whitespace (other than just a newline). Put a marker character
# at the end of the output line so as to make the whitespace visible.

chomp( my @input = <STDIN>);
foreach my $line ( @input ) {
  if ( $line =~ /\s\Z/) {
    print "$line.\n";
  }
}
