#!/usr/bin/perl
use 5.010;
use warnings;
use strict;

# Make a program that prints each line that has a word that is capitalized but
# not ALL capitalized. Does it match Fred but neither fred nor FRED?

say "Please input some strings:";
chomp( my @lines = <STDIN> );
say "Lines containing a word that contains some capital letters, but is not all caps";
foreach ( @lines ) {
  if ( /[A-Z][a-z]+/ ) {
    say $_;
  };
};

