#!/usr/bin/perl
use 5.010;
use warnings;
use strict;

# Extra credit exercise: write a program that prints out any input line that
# mentions both wilma and fred.

say "Please input some strings:";
chomp( my @lines = <STDIN> );
say "output:";
foreach ( @lines ) {
  if ( /(wilma.*fred|fred.*wilma)/ ) {
    say $_;
  };
};

