#!/usr/bin/perl
use 5.014;
use warnings;
use strict;

# Write a program that reads a list of strings (on separate lines) until
# end-of-input. Then it should print the strings in code point order. That
# is, if you enter the strings fred, barney, wilma, betty, the output should
# show barney betty fred wilma. Are all of the strings on one line in the
# output or on separate lines? Could you make the output appear in either
# style?

my $inline = 0;


say "Enter Strings : ";
chomp( my @lines = <STDIN> );
@lines = sort @lines;
print "Sorted Strings : ";
foreach my $line (@lines) {
   if ( $inline ) {
     print "$line ";
   } else {
     print "\n$line";
   };
};
print "\n";
