#!/usr/bin/perl
use 5.010;
use warnings;
use strict;

# Write a program that will ask the user for a given name and
# report the corresponding family name.

my %names = (
    Andrew => 'Davies',
    David => 'Thrussell',
    Alex => 'Deas',
    Dave => 'Cox',
    Sean => 'Clark',
);

print "Please give given name: ";
chomp( my $name = <STDIN> );
if ( $names{$name} ) {
 say "Surname is $names{$name}";
} else {
  say "Name could not be found!";
};
