#!/usr/bin/perl
use 5.010;
use warnings;
use strict;

# Write a program that reads a series of words (with one word per line)
# until end-of-input, then prints a summary of how many times each word was
# seen. (Hint: remember that when an undefined value is used as if it were a
# number, Perl automatically converts it to 0. It may help to look back at the
# earlier exercise that kept a running total.) So, if the input words were
# fred, barney, fred, dino, wilma, fred (all on separate lines), the output
# should tell us that fred was seen 3 times. For extra credit, sort the
# summary words in code point order in the output.


my %wordcount;

say "Please input a single word on each line:";
chomp( my @input = <STDIN> );
foreach my $word ( @input ) {
  $wordcount{$word}++;
};
foreach my $word ( sort keys %wordcount ) {
  say "$word appears $wordcount{$word} times.";
};
